"""
Top 50 Indian Equities — NSE/BSE universe.
yfinance symbols use the .NS suffix for NSE and .BO for BSE.
"""

NSE_TOP_50 = [
    # Symbol (yfinance)   Display name                    Sector
    ("RELIANCE.NS",  "Reliance Industries",           "Energy",          "Oil & Gas"),
    ("TCS.NS",       "Tata Consultancy Services",      "Technology",      "IT Services"),
    ("HDFCBANK.NS",  "HDFC Bank",                      "Financials",      "Private Bank"),
    ("INFY.NS",      "Infosys",                        "Technology",      "IT Services"),
    ("ICICIBANK.NS", "ICICI Bank",                     "Financials",      "Private Bank"),
    ("HINDUNILVR.NS","Hindustan Unilever",              "Consumer Staples","FMCG"),
    ("SBIN.NS",      "State Bank of India",             "Financials",      "Public Bank"),
    ("BHARTIARTL.NS","Bharti Airtel",                   "Communication",   "Telecom"),
    ("ITC.NS",       "ITC Limited",                    "Consumer Staples","FMCG"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank",             "Financials",      "Private Bank"),
    ("LT.NS",        "Larsen & Toubro",                "Industrials",     "Construction"),
    ("HCLTECH.NS",   "HCL Technologies",               "Technology",      "IT Services"),
    ("ASIANPAINT.NS","Asian Paints",                   "Materials",       "Paints"),
    ("AXISBANK.NS",  "Axis Bank",                      "Financials",      "Private Bank"),
    ("MARUTI.NS",    "Maruti Suzuki",                  "Consumer Discret.","Automobiles"),
    ("BAJFINANCE.NS","Bajaj Finance",                  "Financials",      "NBFC"),
    ("WIPRO.NS",     "Wipro",                          "Technology",      "IT Services"),
    ("ULTRACEMCO.NS","UltraTech Cement",               "Materials",       "Cement"),
    ("TITAN.NS",     "Titan Company",                  "Consumer Discret.","Retail"),
    ("NESTLEIND.NS", "Nestlé India",                   "Consumer Staples","FMCG"),
    ("SUNPHARMA.NS", "Sun Pharmaceutical",             "Healthcare",      "Pharma"),
    ("POWERGRID.NS", "Power Grid Corporation",         "Utilities",       "Power"),
    ("NTPC.NS",      "NTPC",                           "Utilities",       "Power"),
    ("ONGC.NS",      "Oil & Natural Gas Corp",         "Energy",          "Oil & Gas"),
    ("M&M.NS",       "Mahindra & Mahindra",            "Consumer Discret.","Automobiles"),
    ("TECHM.NS",     "Tech Mahindra",                  "Technology",      "IT Services"),
    ("JSWSTEEL.NS",  "JSW Steel",                      "Materials",       "Steel"),
    ("TATAMOTORS.NS","Tata Motors",                    "Consumer Discret.","Automobiles"),
    ("HDFCLIFE.NS",  "HDFC Life Insurance",            "Financials",      "Insurance"),
    ("SBILIFE.NS",   "SBI Life Insurance",             "Financials",      "Insurance"),
    ("BAJAJFINSV.NS","Bajaj Finserv",                  "Financials",      "NBFC"),
    ("DIVISLAB.NS",  "Divi's Laboratories",            "Healthcare",      "Pharma"),
    ("DRREDDY.NS",   "Dr Reddy's Laboratories",        "Healthcare",      "Pharma"),
    ("CIPLA.NS",     "Cipla",                          "Healthcare",      "Pharma"),
    ("ADANIPORTS.NS","Adani Ports & SEZ",              "Industrials",     "Infrastructure"),
    ("TATASTEEL.NS", "Tata Steel",                     "Materials",       "Steel"),
    ("COALINDIA.NS", "Coal India",                     "Energy",          "Mining"),
    ("BPCL.NS",      "Bharat Petroleum",               "Energy",          "Oil & Gas"),
    ("GRASIM.NS",    "Grasim Industries",              "Materials",       "Cement"),
    ("EICHERMOT.NS", "Eicher Motors",                  "Consumer Discret.","Automobiles"),
    ("BRITANNIA.NS", "Britannia Industries",           "Consumer Staples","FMCG"),
    ("HEROMOTOCO.NS","Hero MotoCorp",                  "Consumer Discret.","Automobiles"),
    ("APOLLOHOSP.NS","Apollo Hospitals",               "Healthcare",      "Hospitals"),
    ("TATACONSUM.NS","Tata Consumer Products",         "Consumer Staples","FMCG"),
    ("INDUSINDBK.NS","IndusInd Bank",                  "Financials",      "Private Bank"),
    ("UPL.NS",       "UPL",                            "Materials",       "Agrochemicals"),
    ("HINDALCO.NS",  "Hindalco Industries",            "Materials",       "Aluminium"),
    ("VEDL.NS",      "Vedanta",                        "Materials",       "Mining"),
    ("BAJAJ-AUTO.NS","Bajaj Auto",                     "Consumer Discret.","Automobiles"),
    ("SHREECEM.NS",  "Shree Cement",                   "Materials",       "Cement"),
]
